### ISSUE TITLE
menu item shows up after installing but won't show coco controls plugin menu

### ISSUE THREAD

**Issue by moyoteg** [yeahdongcn/CocoaControlsPlugin#5]
I can't get the menu to show! it seems that after installing the plugin with Alcatraz I can see the View>Cocoa Controls menu but after selecting it nothing happens...

**Comment by yeahdongcn** [comment]
Fixed by https://github.com/yeahdongcn/CocoaControlsPlugin/commit/bcbdfa16889a3ef8da217abfddcc944f9725bf34

**Comment by yeahdongcn** [comment]
Please remove the installed one and reinstall it.

**Comment by moyoteg** [comment]
I tried doing that on Xcode Version 6.3.1 (6D1002) but the GUI still doesn't show up after restarting Xcode. =/

**Comment by yeahdongcn** [comment]
Is the menu shows this time?

**Comment by Diwann** [comment]
worked for me. 
I had the same pb and I just reinstalled the plugin with alcatraz

**Comment by FabKremer** [comment]
Doesn't work for me either. I've installed the plugin with Alcatraz

**Comment by moyoteg** [comment]
I have to install it every time I run Xcode so that I can see it.

**Comment by ywwzwb** [comment]
I cann't get the menu,I'm using Xcode 6.4. I've reinstall it with Alcatraz, but it still not show

**Comment by yeahdongcn** [comment]
Fixed by the following commits.

https://github.com/yeahdongcn/CocoaControlsPlugin/commit/b2681017d04f5503f44d79ad399b2988196522ff
https://github.com/yeahdongcn/CocoaControlsPlugin/commit/fd600a591c7803cb17cd198112a75731238d7646
